blank_issues_enabled: true
contact_links:
  - name: Conda-forge Matrix/Element.io chat
    url: https://matrix.to/#/#conda-forge:matrix.org
    about: Chat to us about conda-forge and ask general questions.
  - name: Conda-forge documentation
    url: https://conda-forge.org/docs/
    about: The complete conda-forge documentation.
