blank_issues_enabled: true
contact_links:
  - name: Conda-forge community
    url: https://conda-forge.org/community/getting-in-touch/
    about: Learn where to find to us.
  - name: Conda-forge documentation
    url: https://conda-forge.org/docs/
    about: The complete conda-forge documentation.
